### ISSUE TITLE
Portfolio - main section - desktop

### ISSUE THREAD

**Issue by AvisHowl** [AvisHowl/agency#13]

**Comment by solodolya** [comment]
При уменьшении размера экрана блоки с изображениями наезжают друг на друга, предлагаю их сделать более резиновыми либо предусмотреть постоянное расстояние между ними.

![Image](https://github.com/AvisHowl/agency/assets/161466062/be7f2a57-3b49-4b30-bd3d-ee2f7c86fddc)
![Image](https://github.com/AvisHowl/agency/assets/161466062/85b2dea6-5abb-47cf-9f08-decdedfb6d31)

В остальном всё хорошо, все кнопки и ссылки кликабельны.
