### ISSUE TITLE
Blog Articles - main section - desktop

### ISSUE THREAD

**Issue by AvisHowl** [AvisHowl/agency#16]

**Comment by solodolya** [comment]
@AvisHowl , прошу исправить, пожалуйста, файлик scss для странички blog: убрать лишнее правило для ширины блока.



![Image](https://github.com/AvisHowl/agency/assets/161466062/f5ba22e6-58f5-44cd-94bc-9a53f40b0809)

**Comment by solodolya** [comment]
И чуть ниже в коде прошу удалить padding-right.



![Image](https://github.com/AvisHowl/agency/assets/161466062/d3a26f3e-b134-4ffa-b3bb-8e7b0386dbb5)
