### ISSUE TITLE
About Us - main section - desktop

### ISSUE THREAD

**Issue by AvisHowl** [AvisHowl/agency#19]

**Comment by solodolya** [comment]
В макете в блоках справа расположены стрелки, а на странице их нет.

![Image](https://github.com/AvisHowl/agency/assets/161466062/ba87a4f8-7c40-4057-94b4-fd5a06d77f6b)

**Comment by solodolya** [comment]
Граница блоков должна быть другого цвета.

![Image](https://github.com/AvisHowl/agency/assets/161466062/78a07cb0-05cf-45ca-91b3-e9aecb74c2bf)

Все кнопки и ссылки кликабельны, видео работает, страница при изменении размера ведёт себя отлично.

**Comment by AvisHowl** [comment]
> Граница блоков должна быть другого цвета.
> 
> ![Image](https://private-user-images.githubusercontent.com/161466062/330039833-78a07cb0-05cf-45ca-91b3-e9aecb74c2bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MzI2MTYsIm5iZiI6MTcxNTYzMjMxNiwicGF0aCI6Ii8xNjE0NjYwNjIvMzMwMDM5ODMzLTc4YTA3Y2IwLTA1Y2YtNDVjYS05MWIzLWU5YWVjYjc0YzJiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QyMDMxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDJkMDMyYTY0ZmIyYTg1NzZkNGM0ODY2OTk1NDMzYjFjMWY0MDJmNmUyMzc1YzYyNWJmYzQ5YTZlZGFhYzc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cGXu3DL0QDGblejoxEdUNBqLEhJtjBlSeiKX7niii8E)
> 
> Все кнопки и ссылки кликабельны, видео работает, страница при изменении размера ведёт себя отлично.

Я перепроверила, граница правильного цвета... она темного цвета в десктопе, светлого в мобильной

**Comment by solodolya** [comment]
> > Граница блоков должна быть другого цвета.
> > ![Image](https://private-user-images.githubusercontent.com/161466062/330039833-78a07cb0-05cf-45ca-91b3-e9aecb74c2bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MzI2MTYsIm5iZiI6MTcxNTYzMjMxNiwicGF0aCI6Ii8xNjE0NjYwNjIvMzMwMDM5ODMzLTc4YTA3Y2IwLTA1Y2YtNDVjYS05MWIzLWU5YWVjYjc0YzJiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QyMDMxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDJkMDMyYTY0ZmIyYTg1NzZkNGM0ODY2OTk1NDMzYjFjMWY0MDJmNmUyMzc1YzYyNWJmYzQ5YTZlZGFhYzc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cGXu3DL0QDGblejoxEdUNBqLEhJtjBlSeiKX7niii8E)
> > Все кнопки и ссылки кликабельны, видео работает, страница при изменении размера ведёт себя отлично.
> 
> Я перепроверила, граница правильного цвета... она темного цвета в десктопе, светлого в мобильной

Прикрепляю скрин макета, и в Figma и в Pixso граница светлая в десктопной версии, выделила блок, справа на панели внизу указан цвет границы блока.  

![скрин макета](https://github.com/AvisHowl/agency/assets/161466062/30f59405-13ef-4489-ab23-fe0be29eeebb)
