### ISSUE TITLE
About Us - mobile version

### ISSUE THREAD

**Issue by AvisHowl** [AvisHowl/agency#25]

**Comment by solodolya** [comment]
В блоках справа отсутствуют стрелки.

![Image](https://github.com/AvisHowl/agency/assets/161466062/134ad17a-5973-4165-8b0c-4678918703b0)

**Comment by solodolya** [comment]
В макете блок с отзывом растянут на 100% страницы.

![Image](https://github.com/AvisHowl/agency/assets/161466062/e2ce7b5a-50e1-4b62-905e-972fe7268e9f)

**Comment by solodolya** [comment]
Потерялась ссылка Contact Me между текстом и белым блоком.

![Image](https://github.com/AvisHowl/agency/assets/161466062/f2938e30-cf50-415a-987f-7f91a9894da6)

**Comment by AvisHowl** [comment]
> В макете блок с отзывом растянут на 100% страницы.
> 
> ![Image](https://private-user-images.githubusercontent.com/161466062/330040402-e2ce7b5a-50e1-4b62-905e-972fe7268e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MzI1NDQsIm5iZiI6MTcxNTYzMjI0NCwicGF0aCI6Ii8xNjE0NjYwNjIvMzMwMDQwNDAyLWUyY2U3YjVhLTUwZTEtNGI2Mi05MDVlLTk3MmZlNzI2OGU5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QyMDMwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODEzOTFkMmIyYjA0Mjc0NGE5ZmQwODRhN2UzZGY2Zjk1YTQ2NTg2N2Q2YmU4ZTAxMDg4ZjJhZjVlMTcyNDgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hfl_eXmVzgkP_Za1SXBuTJ5MAPWpjfZwPu9ehKeSKN4)

У меня не получилось растянуть его на 100%, к сожалению. Остальное исправлено

**Comment by solodolya** [comment]
Ссылку Contact Me необходимо перенести после статьи. Вот как на макете:


![Image](https://github.com/AvisHowl/agency/assets/161466062/db571057-b25d-40e3-af9b-8b87b68b77f8)


А сейчас у тебя на страничке это выглядит так:


![Image](https://github.com/AvisHowl/agency/assets/161466062/d4138ec2-3126-44ad-87bf-f3d926e90370)
